### ISSUE TITLE
Doesn't work with wkhtmltopdf 0.12.2.4

### ISSUE THREAD

**Issue by andrewthad** [alexkyllo/yesod-content-pdf#5]
I just upgraded to the newest ubuntu distro, which has wkhtmltopdf 0.12.2.4 in the repos, and yesod-content-pdf doesn't seem to be compatible with it. My co-worker is using version 0.9.9, and it works fine for him.

**Comment by alexkyllo** [comment]
Thanks for reporting. I just tested it with wkhtmltopdf 0.12.3 on Ubuntu and it worked fine. On http://wkhtmltopdf.org/downloads.html they don't have a 0.12.2.4 binary for Linux, only Windows, and I don't have a Windows machine that I can test on right now. Does your wkhtmltopdf work by itself on your machine--you have all its dependencies properly installed? Are you getting any error message?
